- name: Install core CLI utilities
  become: true
  package:
    name:
      - autoconf
      - atool
      - ansible
      - curl
      - default-jre
      - ffmpeg
      - fzf
      - gcc
      - git
      - htop
      - libtool
      - lm-sensors
      - make
      - man
      - most
      - ncal
      - neofetch
      - neovim
      - network-manager
      - npm
      - pass
      - pipx
      - ssh
      - stow
      - sudo
      - tmux
      - tree
      - unzip
      - wget
      - zsh
  tags:
    - base
    - install
    - core

- name: Install extra CLI utilities
  become: true
  package:
    name:
      - dictd
      - dict-gcide
      - dict-wn
      - isync
      - neomutt
      - orpie
      - rtorrent
      - newsboat
      - w3m
      - w3m-img
  tags:
    - install
    - cli-extras

- name: Install Xorg, WM, and GUI utilities
  become: true
  package:
    name:
      - alsa-utils
      - feh
      - fonts-noto-color-emoji
      - mpv
      - picom
      - pulseaudio
      - rxvt-unicode
      - scrot
      - slock
      - x11-utils
      - x11-xserver-utils
      - xinit
      - xinput
      - xserver-xorg-core
      - xserver-xorg-input-libinput
      - xcb 
      - xutils-dev
      - libxcb-xkb-dev 
      - x11-xkb-utils 
      - libx11-xcb-dev 
      - libxkbcommon-x11-dev 
      - libxtst-dev
      - libx11-dev
      - libxinerama-dev
      - libxft-dev
      - libxcb-res0-dev
      - zathura
  tags:
    - base
    - install
    - xorg
