- name: Stow CLI configs
  shell: "stow -d ../dotfiles -t ~/ -v --adopt {{ item }}"
  loop:
    - htop
    - tmux
    - nvim
    - zsh
  tags:
    - base
    - config
    - stow
    - core

- name: Stow CLI extras
  shell: "stow -d ../dotfiles -t ~/ -v --adopt {{ item }}"
  loop:
    - newsboat
  tags:
    - config
    - stow
    - cli-extras

- name: Stow xorg, wm, and wm utility configs
  shell: "stow -d ../dotfiles -t ~/ -v --adopt {{ item }}"
  loop:
    - picom
    - x-windows
  tags:
    - base
    - config
    - stow
    - xorg

- name: Set zsh as default shell
  become: true
  shell: chsh -s /bin/zsh
  tags:
    - base
    - config
    - zsh

- name: Link scripts
  file:
    src: "{{ playbook_dir }}/../Scripts"
    dest: "~/Scripts"
    state: link
    force: true
  tags:
    - base
    - config
    - technobar
