- name: Install core CLI utilities
  become: true
  package:
    name:
      - ansible
      - atool
      - autoconf
      - bc
      - curl
      - default-jre
      - ffmpeg
      - fzf
      - gcc
      - git
      - htop
      - libtool
      - lm-sensors
      - make
      - man
      - ncal
      - neovim
      - network-manager
      - pass
      - pipx
      - ssh
      - stow
      - sudo
      - tree
      - unzip
      - wget
      - zsh
  tags:
    - base
    - install
    - core

- name: Install extra CLI utilities
  become: true
  package:
    name:
      - cowsay
      - dict-gcide
      - dict-wn
      - dictd
      - fortune
      - gdb
      - neofetch
      - orpie
      - texlive-full
      - valgrind
      - wine
  tags:
    - install
    - cli-extras

- name: Install Xorg, WM, and GUI utilities
  become: true
  package:
    name:
      - alsa-utils
      - arandr
      - autorandr
      - compton
      - feh
      - fonts-noto-color-emoji
      - i3lock
      - libsdl2-image-2.0-0 
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libx11-dev
      - libx11-xcb-dev 
      - libxcb-res0-dev
      - libxcb-xkb-dev 
      - libxft-dev
      - libxinerama-dev
      - libxkbcommon-x11-dev 
      - libxrandr-dev
      - libxtst-dev
      - mpv
      - numlockx
      - pavucontrol
      - pulseaudio
      - pulseaudio-module-bluetooth
      - pulsemixer
      - rofi
      - scrot
      - unifont
      - x11-utils
      - x11-xkb-utils 
      - x11-xserver-utils
      - xcb 
      - xfonts-terminus
      - xinit
      - xinput
      - xserver-xorg-core
      - xserver-xorg-input-libinput
      - xss-lock
      - xutils-dev
      - zathura
  tags:
    - base
    - install
    - xorg
