- name: Install flatpak
  become: true
  package:
    name:
      - flatpak
  tags:
    - flatpak
    - install

- name: Add flathub repo
  become: true
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
    - install

- name: Install flatpak GUI extras
  flatpak:
    name:
      - com.github.corna.Vivado
      - com.github.tchx84.Flatseal
      - com.spotify.Client
      - com.valvesoftware.Steam
      - org.inkscape.Inkscape
      - org.freedesktop.Platform.GL32.nvidia-525-147-05
      - org.kde.krita
      - org.qbittorrent.qBittorrent
      - org.signal.Signal
      - org.tenacityaudio.Tenacity
      - us.zoom.Zoom
  tags:
    - flatpak
    - install
    - gui-extras
