- name: Install flatpak
  become: true
  package:
    name:
      - flatpak
  tags:
    - flatpak
    - install

- name: Add flathub repo
  become: true
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
    - install

- name: Install flatpak GUI extras
  flatpak:
    name:
      - com.github.tchx84.Flatseal
      - com.spotify.Client
      - com.vivaldi.Vivaldi
      - org.kde.krita
      - org.tenacityaudio.Tenacity
      - org.qbittorrent.qBittorrent
      - org.signal.Signal
  tags:
    - flatpak
    - install
    - gui-extras
