- name: Install flatpak
  become: true
  package:
    name:
      - flatpak
  tags:
    - flatpak
    - install

- name: Add flathub repo
  become: true
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
    - install

- name: Install flatpak GUI extras
  flatpak:
    name:
      - com.discordapp.Discord
      - org.kde.krita
      - com.mojang.Minecraft
      - io.github.hrkfdn.ncspot
      - org.shotcut.Shotcut
      - org.tenacityaudio.Tenacity
      - org.signal.Signal
      - com.valvesoftware.Steam
      - us.zoom.Zoom
  tags:
    - flatpak
    - install
    - gui-extras
