- name: Install CLI utilities
  become: true
  package:
    name:
      - git
      - htop
      - lm-sensors
      - man
      - most
      - ncal
      - neofetch
      - neovim
      - network-manager
      - orpie
      - ssh
      - stow
      - sudo
      - tmux
      - tree
      - unzip
      - wget
      - zsh
  tags:
    - base
    - core
    - install

- name: Install Xorg, WM, and WM utilities
  become: true
  package:
    name:
      - alsa-utils
      - conky
      - feh
      - picom
      - pulseaudio
      - rxvt-unicode
      - scrot
      - spectrwm
      - x11-utils
      - x11-xserver-utils
      - xinit
      - xscreensaver
      - xserver-xorg-core
      - xserver-xorg-input-libinput
  tags:
    - base
    - install
    - xorg

- name: Install GUI utilities
  become: true
  package:
    name:
      - audacity
      - ffmpeg
      - krita
      - shotcut
      - vlc
  tags:
    - base
    - gui-utils
    - install

- name: Install ThinkPad utilities
  become: true
  package:
    name:
      - autorandr
      - light
      - tlp
  tags:
    - install
    - thinkpad
