- name: Download kjv Bible
  become: true
  git:
    repo: https://github.com/lukesmithxyz/kjv.git
    dest: /tmp/kjv
    force: true
  tags:
    - install
    - cli-extras
    - kjv

- name: Install kjv Bible
  become: true
  make:
    chdir: /tmp/kjv
  tags:
    - install
    - cli-extras
    - kjv
