- name: Install nvidia drivers
  become: true
  package:
    name:
      - nvidia-driver
  tags:
    - install
    - nvidia

- name: Configure nvidia wake scripts
  become: true
  file:
    src: "{{ playbook_dir }}/../dotfiles/tlp/tlp.conf"
    dest: "/etc/tlp.conf"
    state: link
    force: true
  tags:
    - config
    - laptop
    - tlp
