- name: Make and install Suckless utils
  become: true
  make:
    chdir: "{{ playbook_dir }}/../sources/{{ item.name }}"
    target: install
  loop:
    - { name: 'dwm' }
    - { name: 'st' }
    - { name: 'dwmblocks' }
  tags:
    - base
    - install
    - suckless

