- name: Check for existing Vivaldi install
  stat:
    path: /usr/bin/vivaldi-stable
  register: vivaldi_var

- name: Install Vivaldi
  become: true
  apt:
    deb: https://downloads.vivaldi.com/stable/vivaldi-stable_6.1.3035.111-1_amd64.deb
  when: not vivaldi_var.stat.exists
  tags:
    - install
    - vivaldi
