- name: Hayden's automated Debian setup script
  hosts: localhost

  pre_tasks:
    - name: Add non-free, contrib repos
      become: true
      replace:
        path: /etc/apt/sources.list
        regexp: '(non-free-firmware)$'
        replace: 'contrib non-free'
      tags:
        - base
        - install

    - name: Upgrade package list
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - base
        - install

    - name: Make home directories
      file:
        path: "{{ lookup('env', 'HOME') }}/{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "Documents"
        - "Downloads"
        - "Photos"
        - "Games"
        - "Git"
        - "Photos/Screenshots"
        - "Photos/Wallpapers"
      tags:
        - base
        - config

  tasks:
    - include: tasks/base-install.yml
    - include: tasks/base-config.yml
    - include: tasks/flatpak-install.yml
    - include: tasks/vivaldi.yml
    - include: tasks/cdda.yml
